backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://www.sebastien-odd.tattoo/
collections:
  - name: "artistes"
    label: "Artistes" 
    folder: "content/artistes/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image", required: true}
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Description", name: "description", widget: "markdown", required: true}
      - {label: "Galerie", name: "galerie", widget: "list", field: {label: Image, name: image, widget: image}}
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - {label: "Miniature", name: "thumbnail", widget: "image", required: true}
  - name: "blog"
    label: "Blog" 
    folder: "content/blog/posts"
    create: true
    slug: "{{years}}-{{month}}-{{day}}-{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Intro", name: "intro", widget: "markdown", required: false}
      - {label: "Article", name: "article", widget: "markdown"}
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
