backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://electro-alternativ-2019.netlify.com/
collections:
  - name: "artistes"
    label: "Artistes"
    folder: "content/artistes/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image", required: true}
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Iframe", name: "iframe", widget: "markdown"}
      - {label: "Langue", name: "langue", widget: "string"}
      - {label: "Label", name: "label", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - { label: Lien, name: lien, widget: string }
          - { label: awesome, name: awesome, widget: string }
  - name: "lieux"
    label: "Lieux"
    folder: "content/lieux/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image", required: true}
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Iframe", name: "iframe", widget: "markdown"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "GMAP"
        name: "gmap"
        widget: "list"
        fields:
          - { label: awesome, name: awesome, widget: string }
          - { label: Texte, name: texte, widget: string }
          - { label: Lien, name: lien, widget: string }
      - {label: "Direction", name: "direction", widget: "string"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - {label: "Miniature", name: "thumbnail", widget: "image"}
      - label: "Evenement"
        name: "Evenement"
        widget: "list"
        fields:
          - label: "Events"
            name: "events"
            widget: "relation"
            collection: "event"
            searchFields: ["title"]
            valueField: "title"
            displayFields: ["title"]
            multiple: "true"
  - name: "event"
    label: "Evenements"
    folder: "content/evenements/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Date", name: "dateevents", widget: "date", format: "DD/MM/YYYY"}
      - {label: "Heure de début", name: "start", widget: "string"}
      - {label: "Heure de fin", name: "end", widget: "string"}
<<<<<<< HEAD
=======
      - label: "Semaine"
        name: "background"
        widget: "select"
        options:
          - { label: "Semaine 1", value: "semaine1" }
          - { label: "Semaine 2", value: "semaine2" }
          - { label: "Semaine 3", value: "semaine3" }
          - { label: "Semaine 4", value: "semaine4" }
>>>>>>> b6fa6323564df891d3a99c1b024c5e7725b8feae
      - label: "Groupes"
        name: "groupes"
        widget: "list"
        fields:
          - label: "Artiste"
            name: "artiste"
            widget: "relation"
            collection: "artistes"
            searchFields: ["title"]
            valueField: "url"
            displayFields: ["title"]
            multiple: "true"
      - {label: "Galerie", name: "galerie", widget: "list", field: {label: Image, name: image, widget: image}}
      - label: "Lieu"
        name: "lieu"
        widget: "relation"
        collection: "lieux"
        searchFields: ["title"]
        valueField: "url"
        displayFields: ["title"]
        multiple: "true"
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - label: "Images de fond"
        name: "background"
        widget: "select"
        options:
          - { label: "Background 1", value: "/images/background-1-electro-alternativ.jpg" }
          - { label: "Background 2", value: "/images/background-2-electro-alternativ.jpg" }
          - { label: "Background 3", value: "/images/background-3-electro-alternativ.jpg" }
          - { label: "Background 4", value: "/images/background-4-electro-alternativ.jpg" }
          - { label: "Background 5", value: "/images/background-5-electro-alternativ.jpg" }
      - {label: "Miniature", name: "thumbnail", widget: "image"}
  - name: "articles"
    label: "Articles"
    folder: "content/articles/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image", required: true}
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Intro", name: "intro", widget: "markdown"}
      - {label: "Article", name: "article", widget: "markdown"}
      - label: "Liens"
        name: "liens"
        widget: "list"
        fields:
          - { label: Lien, name: lien, widget: string }
          - { label: awesome, name: awesome, widget: string }
