backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://1plus2.netlify.com/
collections:
  - name: "actualites"
    label: "Actualites"
    folder: "content/actualites/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "titre", widget: "string", tagname: "h1", required: true}
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "thumbnail", widget: "image", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "editions"
    label: "Editions"
    folder: "content/editions/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "titre", widget: "string", tagname: "h1", required: true}
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "thumbnail", widget: "image", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "factory"
    label: "Factory"
    folder: "content/factory/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "titre", widget: "string", tagname: "h1", required: true}
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "thumbnail", widget: "image", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "film"
    label: "Film"
    folder: "content/film/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Titre", name: "titre", widget: "string", tagname: "h1", required: true}
      - {label: "Intro", name: "description", widget: "markdown", required: false}
      - {label: "Article", name: "article", widget: "markdown", required: false}
      - {label: "Iframe", name: "iframe", widget: "markdown", required: false}
      - {label: "Galerie", name: "galerie", widget: "list", field: {label: Image, name: image, widget: image}, required: false}
      - {label: "Description SEO", name: "thumbnail", widget: "image", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
