backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://www.sebastien-odd.tattoo/
collections:
  - name: "artistes"
    label: "Artistes" 
    folder: "content/artistes/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image", required: true}
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Iframe", name: "iframe", widget: "markdown"}
      - label: "Date"
        name: "dateshow"
        widget: "select"
        options:
          - { label: "02/08", value: "vendredi" }
          - { label: "03/08", value: "samedi" }
      - label: "Stages"
        name: "stage"
        widget: "select"
        options:
          - { label: "R2-D2 / TECHNO", value: "TECHNO" }
          - { label: "T-800 / HARDCORE", value: "HARDCORE" }
          - { label: "WALL-E / TRANCE", value: "TRANCE" }
          - { label: "C3-PO / HIP HOP", value: "HIPHOP" }
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - {label: "Miniature", name: "thumbnail", widget: "image", required: true}
  - name: "blog"
    label: "Blog" 
    folder: "content/blog/posts"
    create: true
    slug: "{{years}}-{{month}}-{{day}}-{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "thumbnail", widget: "image"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Intro", name: "intro", widget: "markdown", required: false}
      - {label: "Article", name: "article", widget: "markdown"}
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
