backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://1plus2.netlify.com/
collections:
  - name: "actualites"
    label: "Actualites"
    folder: "content/actualites/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "editions"
    label: "Editions"
    folder: "content/editions/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "factory"
    label: "Factory"
    folder: "content/factory/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "films"
    label: "Films"
    folder: "content/films/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY", required: false}
      - label: "Article"
        name: "body"
        widget: "object"
        fields: 
          - {label: "Intro", name: "description", widget: "markdown", required: false}
          - {label: "Article", name: "content", widget: "markdown", required: false}
          - label: "En savoir plus"
            name: "readmore"
            widget: "object"
            fields:
              - { label: Texte, name: readtexte, widget: string }
              - { label: Lien, name: readlien, widget: string }
          - label: "Liens"
            name: "link"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields: 
          - {label: "Iframe", name: "iframe", widget: "markdown", required: false}
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields: 
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
