backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://1plus2.netlify.com/
collections:
  - name: "actualites"
    label: "Actualites"
    folder: "content/actualites/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - label: "Catégories"
          name: "categories"
          widget: "relation"
          collection: "categorie"
          searchFields: ["title"]
          valueField: "title"
          displayFields: ["title"]
      - {label: "Article", name: "description", widget: "markdown", required: false}
      - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
      - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "categorie"
    label: "Categorie"
    folder: "content/categorie/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
  - name: "films"
    label: "Films"
    folder: "content/films/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY/MM/DD", required: true}
      - label: "Article"
        name: "body"
        widget: "object"
        fields:
          - {label: "Intro", name: "description", widget: "markdown", required: false}
          - {label: "Article", name: "content", widget: "markdown", required: false}
          - label: "En savoir plus"
            name: "readmore"
            widget: "object"
            fields:
              - { label: Texte, name: readtexte, widget: string }
              - { label: Lien, name: readlien, widget: string }
          - label: "Liens"
            name: "link"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields:
          - {label: "Iframe", name: "iframe", widget: "markdown", required: false}
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "factory"
    label: "Factory"
    folder: "content/factory/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY/MM/DD", required: true}
      - label: "Article"
        name: "body"
        widget: "object"
        fields:
          - {label: "Intro", name: "description", widget: "markdown", required: false}
          - {label: "Article", name: "content", widget: "markdown", required: false}
          - {label: "Informations", name: "readmore", widget: "markdown", required: false}
          - label: "Liens"
            name: "link"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "editions"
    label: "Editions"
    folder: "content/editions/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY/MM/DD", required: true}
      - label: "Article"
        name: "body"
        widget: "object"
        fields:
          - {label: "Informations", name: "description", widget: "markdown", required: false}
          - label: "Commander"
            name: "commander"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
          - {label: "Article", name: "content", widget: "markdown", required: false}
          - label: "En savoir plus"
            name: "savoirplus"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
          - label: "Liens"
            name: "link"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "horslesmurs"
    label: "Hors Les Murs"
    folder: "content/hors-les-murs/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY/MM/DD", required: true}
      - label: "Article"
        name: "body"
        widget: "object"
        fields:
          - {label: "Intro", name: "description", widget: "markdown", required: false}
          - {label: "Article", name: "content", widget: "markdown", required: false}
          - {label: "Informations", name: "readmore", widget: "markdown", required: false}
          - label: "Liens"
            name: "link"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "expositions"
    label: "Expositions"
    folder: "content/expositions/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY/MM/DD", required: true}
      - {label: "Horaires", name: "horaires", widget: "string", required: false}
      - label: "Article"
        name: "body"
        widget: "object"
        fields:
          - {label: "Intro", name: "description", widget: "markdown", required: false}
          - {label: "Article", name: "content", widget: "markdown", required: false}
          - label: "En savoir plus"
            name: "readmore"
            widget: "object"
            fields:
              - { label: Texte, name: readtexte, widget: string }
              - { label: Lien, name: readlien, widget: string }
          - label: "Liens"
            name: "link"
            widget: "list"
            required: false
            fields:
              - { label: Texte, name: linktexte, widget: string }
              - { label: Lien, name: linklien, widget: string }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
  - name: "colloques"
    label: "Colloques"
    folder: "content/colloques/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "cover", widget: "image", required: false}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Sous titre", name: "soustitre", widget: "string", required: false}
      - {label: "Horaires", name: "horaires", widget: "string", required: false}
      - label: "Article"
        name: "body"
        widget: "object"
        fields:
          - {label: "Intro", name: "description", widget: "markdown", required: false}
          - label: "Accordeon"
            name: "accordeon"
            widget: "list"
            required: false
            fields:
              - { label: Horaire, name: horaire, widget: string }
              - { label: Titre, name: titre, widget: string }
              - label: "Article"
                name: "article"
                widget: "list"
                required: false
                fields:
                  - { label: Horaire, name: horaire, widget: string }
                  - { label: Information, name: information, widget: markdown }
      - label: "Galeries"
        name: "galeries"
        widget: "object"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            required: false
            fields:
              - { label: image, name: image, widget: image }
              - { label: alt, name: alt, widget: string }
      - label: "SEO"
        name: "seo"
        widget: "object"
        fields:
          - {label: "Description SEO", name: "descriptionseo", widget: "text", required: false}
          - {label: "Miniature SEO", name: "thumbnail", widget: "image", required: false}
