backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://electro-alternativ-2019.netlify.com/
collections:
  - name: "artistes"
    label: "Artistes" 
    folder: "content/artistes/page"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image de couverture", name: "couverture", widget: "image", required: true}
      - {label: "Nom", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Iframe", name: "iframe", widget: "markdown"}
      - label: "Social"
        name: "social"
        widget: "list"
        fields:
          - { label: Lien, name: lien, widget: string }
          - { label: awesome, name: awesome, widget: string }
      - label: "Date"
        name: "dateshow"
        widget: "select"
        options:
          - { label: "VEN. 02 AOÛT", value: "vendredi" }
          - { label: "SAM. 03 AOÛT", value: "samedi" }
      - label: "Stages"
        name: "stage"
        widget: "select"
        options:
          - { label: "R2-D2 / TECHNO", value: "TECHNO" }
          - { label: "T-800 / HARDCORE", value: "HARDCORE" }
          - { label: "WALL-E / TRANCE", value: "TRANCE" }
          - { label: "C3-PO / HIP HOP", value: "HIPHOP" } 
      - {label: "Date de publication", name: "date", widget: "date", format: "DD/MM/YYYY"}
      - {label: "Miniature", name: "thumbnail", widget: "image"}
